#!/usr/bin/env sh

echo Running pre-commit hook

# Check for required binaries, otherwise don't run
for cmd in grep sed xargs; do
    if ! command -v "$cmd" &> /dev/null
    then
        echo "$cmd could not be found - skipping pre-commit"
        exit 0
    fi
done

# Run pre-commit, this checks if we changed any golang files and runs the checks.
# The files are then git-added
FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep .go | sed 's| |\\ |g')
if [ -n "$FILES" ]; then
    make format
    make lint
    if [ $? -ne 0 ]; then
            echo "Error running make check - please fix before committing"
        echo "if this is a mistake you can skip the checks with 'git commit --no-verify'"
        exit 1
    fi
    echo "$FILES" | xargs git add
fi

exit 0
